export const PROVIDERS_TOKENS = {
  CORE_UNIT_OF_WORK: Symbol('CORE_UNIT_OF_WORK'),
  READER_REPOSITORY: Symbol('READER_REPOSITORY'),
  AGE_VERIFICATION_REPOSITORY: Symbol('AGE_VERIFICATION_REPOSITORY'),
  SOCIAL_MEDIA_LINK_REPOSITORY: Symbol('SOCIAL_MEDIA_LINK_REPOSITORY'),
  STORAGE: Symbol('STORAGE'),
  IMAGE_PROCESSOR: Symbol('IMAGE_PROCESSOR'),
} as const;